'use client';

import { useState, useEffect } from 'react';
import { Button } from '@/components/ui/button';
import { Card, CardContent } from '@/components/ui/card';
import { Badge } from '@/components/ui/badge';
import { 
  Dialog, 
  DialogContent, 
  DialogHeader, 
  DialogTitle, 
  DialogDescription 
} from '@/components/ui/dialog';
import { 
  QrCode, 
  Copy, 
  Printer, 
  RefreshCw,
  Users,
  AlertCircle
} from 'lucide-react';
import { createClient } from '@/lib/supabase/client';

interface AssignQRCodeModalProps {
  isOpen: boolean;
  onClose: () => void;
  venueId: string;
  tableId: string;
  tableLabel: string;
}

interface QRData {
  table_id: string;
  table_label: string;
  venue_id: string;
  qr_version: number;
  qr_url: string;
  is_merged: boolean;
  merged_tables?: string[];
}

export function AssignQRCodeModal({
  isOpen,
  onClose,
  venueId,
  tableId,
  tableLabel
}: AssignQRCodeModalProps) {
  const [qrData, setQrData] = useState<QRData | null>(null);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [isRegenerating, setIsRegenerating] = useState(false);

  const supabase = createClient();

  useEffect(() => {
    if (isOpen && tableId) {
      fetchQRData();
    }
  }, [isOpen, tableId]);

  const fetchQRData = async () => {
    try {
      setLoading(true);
      setError(null);

      // Get table details and QR version
      const { data: table, error: tableError } = await supabase
        .from('tables')
        .select('qr_version, merged_with')
        .eq('id', tableId)
        .eq('venue_id', venueId)
        .single();

      if (tableError) throw tableError;

      // Check if table is merged
      const isMerged = !!table.merged_with;
      let mergedTables: string[] = [];

      if (isMerged) {
        // Get all tables in the merge group
        const { data: mergedTableData, error: mergedError } = await supabase
          .from('tables')
          .select('label')
          .eq('merged_with', table.merged_with)
          .eq('venue_id', venueId);

        if (mergedError) throw mergedError;
        mergedTables = mergedTableData.map((t: any) => t.label);
      }

      const qrVersion = table.qr_version || 1;
      const qrUrl = `${window.location.origin}/order?venue=${venueId}&table=${tableLabel}&v=${qrVersion}`;

      setQrData({
        table_id: tableId,
        table_label: tableLabel,
        venue_id: venueId,
        qr_version: qrVersion,
        qr_url: qrUrl,
        is_merged: isMerged,
        merged_tables: mergedTables
      });
    } catch (err) {
      console.error('[ASSIGN QR] Error fetching QR data:', err);
      setError(err instanceof Error ? err.message : 'Failed to load QR data');
    } finally {
      setLoading(false);
    }
  };

  const handleCopyLink = async () => {
    if (!qrData) return;
    
    try {
      await navigator.clipboard.writeText(qrData.qr_url);
      // You could add a toast notification here
    } catch (err) {
      console.error('Failed to copy link:', err);
    }
  };

  const handlePrint = () => {
    if (!qrData) return;
    
    // Create a print-friendly version
    const printWindow = window.open('', '_blank');
    if (printWindow) {
      printWindow.document.write(`
        <html>
          <head>
            <title>QR Code - Table ${qrData.table_label}</title>
            <style>
              body { font-family: Arial, sans-serif; text-align: center; padding: 20px; }
              .qr-container { margin: 20px 0; }
              .qr-code { width: 200px; height: 200px; border: 2px solid #000; margin: 0 auto; display: flex; align-items: center; justify-content: center; background: #fff; }
              .table-info { margin: 20px 0; }
              .url { word-break: break-all; margin: 10px 0; }
            </style>
          </head>
          <body>
            <h1>Table ${qrData.table_label}</h1>
            <div class="qr-container">
              <div class="qr-code">
                <div style="font-size: 12px; text-align: center;">
                  QR Code<br/>
                  (Generated by Servio)
                </div>
              </div>
            </div>
            <div class="table-info">
              <p><strong>Table:</strong> ${qrData.table_label}</p>
              <p><strong>Version:</strong> ${qrData.qr_version}</p>
              ${qrData.is_merged ? `<p><strong>Merged Tables:</strong> ${qrData.merged_tables?.join(', ')}</p>` : ''}
            </div>
            <div class="url">
              <strong>URL:</strong><br/>
              ${qrData.qr_url}
            </div>
          </body>
        </html>
      `);
      printWindow.document.close();
      printWindow.print();
    }
  };

  const handleRegenerate = async () => {
    if (!qrData) return;
    
    try {
      setIsRegenerating(true);
      setError(null);

      // Increment QR version to invalidate old stickers
      const { error: updateError } = await supabase
        .from('tables')
        .update({ 
          qr_version: qrData.qr_version + 1,
          updated_at: new Date().toISOString()
        })
        .eq('id', tableId)
        .eq('venue_id', venueId);

      if (updateError) throw updateError;

      // Refresh QR data
      await fetchQRData();
    } catch (err) {
      console.error('[ASSIGN QR] Error regenerating QR:', err);
      setError(err instanceof Error ? err.message : 'Failed to regenerate QR code');
    } finally {
      setIsRegenerating(false);
    }
  };

  return (
    <Dialog open={isOpen} onOpenChange={onClose}>
      <DialogContent className="max-w-md">
        <DialogHeader>
          <DialogTitle className="flex items-center gap-2">
            <QrCode className="h-5 w-5" />
            Assign QR Code - Table {tableLabel}
          </DialogTitle>
          <DialogDescription>
            Manage QR code assignment for this table
          </DialogDescription>
        </DialogHeader>

        {loading ? (
          <div className="flex items-center justify-center py-8">
            <div className="animate-spin rounded-full h-8 w-8 border-b-2 border-purple-600"></div>
          </div>
        ) : error ? (
          <div className="flex items-center gap-2 text-red-600 py-4">
            <AlertCircle className="h-4 w-4" />
            <span>{error}</span>
          </div>
        ) : qrData ? (
          <div className="space-y-4">
            {/* Current Assignment */}
            <Card>
              <CardContent className="p-4">
                <div className="text-center space-y-3">
                  <div className="bg-white p-4 rounded-lg border-2 border-gray-200 inline-block">
                    <div className="w-32 h-32 bg-gray-100 rounded flex items-center justify-center">
                      <QrCode className="h-16 w-16 text-gray-700" />
                    </div>
                  </div>
                  
                  <div className="space-y-2">
                    <div className="flex items-center justify-center gap-2">
                      <span className="font-semibold">Table {qrData.table_label}</span>
                      <Badge variant="outline">v{qrData.qr_version}</Badge>
                    </div>
                    
                    {qrData.is_merged && qrData.merged_tables && (
                      <div className="text-sm text-blue-600">
                        <Users className="h-4 w-4 inline mr-1" />
                        Merged with: {qrData.merged_tables.join(', ')}
                      </div>
                    )}
                  </div>
                </div>
              </CardContent>
            </Card>

            {/* URL Display */}
            <div className="space-y-2">
              <label className="text-sm font-medium text-gray-700">QR Code URL:</label>
              <div className="p-3 bg-gray-50 rounded-lg border text-sm font-mono break-all">
                {qrData.qr_url}
              </div>
            </div>

            {/* Merge Information */}
            {qrData.is_merged && (
              <div className="p-3 bg-blue-50 rounded-lg border border-blue-200">
                <div className="flex items-start gap-2">
                  <Users className="h-4 w-4 text-blue-600 mt-0.5" />
                  <div className="text-sm text-blue-800">
                    <p className="font-medium">Merged Table</p>
                    <p>Scanning any secondary table's QR will route to the primary session.</p>
                  </div>
                </div>
              </div>
            )}

            {/* Actions */}
            <div className="flex gap-2">
              <Button 
                variant="outline" 
                className="flex-1"
                onClick={handleCopyLink}
              >
                <Copy className="h-4 w-4 mr-2" />
                Copy Link
              </Button>
              <Button 
                variant="outline" 
                className="flex-1"
                onClick={handlePrint}
              >
                <Printer className="h-4 w-4 mr-2" />
                Print
              </Button>
            </div>
            
            <Button 
              variant="outline" 
              className="w-full"
              onClick={handleRegenerate}
              disabled={isRegenerating}
            >
              {isRegenerating ? (
                <>
                  <div className="animate-spin rounded-full h-4 w-4 border-b-2 border-gray-600 mr-2" />
                  Regenerating...
                </>
              ) : (
                <>
                  <RefreshCw className="h-4 w-4 mr-2" />
                  Regenerate QR Code
                </>
              )}
            </Button>
          </div>
        ) : null}
      </DialogContent>
    </Dialog>
  );
}
