# Actionlint configuration
# Suppress warnings for secrets that are defined in repository settings
self-hosted-runner:
  labels: []
shellcheck:
  enabled: false
pyflakes:
  enabled: false
# Path-specific configurations to suppress false positive warnings
paths:
  # Suppress "Context access might be invalid" warnings for all workflow files
  # These are false positives - secrets are valid but may not be configured in all environments
  '.github/workflows/**/*.{yml,yaml}':
    ignore:
      - '.*Context access might be invalid.*'
      - 'Context access might be invalid: NEXT_PUBLIC_SUPABASE_URL'
      - 'Context access might be invalid: NEXT_PUBLIC_SUPABASE_ANON_KEY'
      - 'Context access might be invalid: DATABASE_URL'
      - 'Context access might be invalid: SNYK_TOKEN'
      - 'Context access might be invalid: RAILWAY_TOKEN'
